[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "CaLM"
version = "0.1.2"
description = "CaLM: the Codon adaptation Language Model"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "BSD 3-clause license"}
maintainers = [
    {name = "Carlos Outeiral", email = "carlos@outeiral.net"},
]
dependencies = [
    "numpy",
    "pandas",
    "requests",
    "torch>=1.6",
    "biopython",
    "einops",
    "rotary_embedding_torch",
    "datasets"
]

[tool.setuptools.packages.find]
include = ["calm", "calm.*"]

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]

[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://github.com/oxpig/CaLM"
"Bug Tracker" = "https://github.com/oxpig/CaLM/issues"
